Feature/setup
fbclh/bookstore pull request #1
Opened 2022-04-28 22:32 UTC by fbclh

2022-04-28 23:28 UTC, rukundoeric requested changes
Hi @fbclh, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-28 23:28 UTC, rukundoeric commented on src/components/Book.js
> +        {/* <button type="button">Edit</button> */}
- [ ] <b>REQUIRED:</b> To make sure that your codebase is always clean, remember to remove commented-codes.

2022-04-28 23:28 UTC, rukundoeric commented on src/components/BooksList.js
> +        // category={book.category}
- [ ] <b>REQUIRED:</b> To make sure that your codebase is always clean, remember to remove commented-codes.

2022-04-29 00:15 UTC, rloterh commented on src/components/Book.js
> +        {/* <button type="button">Edit</button> */}
This issue is well resolved! ✔️

2022-04-29 00:15 UTC, rloterh commented on src/components/BooksList.js
> +        // category={book.category}
This issue is well resolved! ✔️

2022-04-29 00:17 UTC, rloterh approved these changes
Hi Fabio, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 00:34 UTC, merged